Repository sighupio/permission-manager, pull requests merged in 2023-01, with the labels that each got.

#109 fix-cert-and-token
  internal/resources/secrets.go
  internal/resources/serviceaccount.go
Labels: bug, enhancement

#97 Move permission templates to values
  helm_chart/templates/seed.yaml
  helm_chart/templates/seed.yml
  helm_chart/values.yaml
Labels: enhancement

#133 Replace broken SIGHUP's logo
  web-client/public/brand-logo.png
  web-client/src/components/Footer.tsx
Labels: bug

#136 Replace hardcoded basicauthpassword's field value
  helm_chart/templates/secret.yaml
  helm_chart/values.yaml
Labels: enhancement, helm
